### ISSUE TITLE
Erro ao fazer download do programa

### ISSUE THREAD

**Issue by plckr** [falsovsky/RTPapd#1]
Boa tarde,

Estou a tentar fazer download do programa `p1222` -> https://www.rtp.pt/play/p1222/bem-vindos-a-beirais

Este é o comando que uso:
```
python .\rtp.py 1222 
```

Erro:
```python
Scraping Page 1 (https://www.rtp.pt/play/bg_l_ep/?listProgram=1222&page=1)
Traceback (most recent call last):
  File ".\rtp.py", line 84, in <module>
    for episode in parse_episodes(progId):
  File ".\rtp.py", line 44, in parse_episodes
    episode_date.text.strip(),
AttributeError: 'NoneType' object has no attribute 'text'
```

O que poderá ser?

**Comment by falsovsky** [comment]
Pelos vistos esse programa nao tem data definida, já tento ver isso :-)

**Comment by falsovsky** [comment]
Carissimo, isso nao é um "podcast". Parecem-me ser videos.

> RTPapd
> RTP audio podcasts downloader

Este script não serve para o que pretendes.

--

Em relação aos videos, até há algum tempo dava para fazer download com o youtube-dl, mas a RTP recentemente decidiu *ofuscar* os URLs dos videos com codigo farsola Javascript.

**Comment by falsovsky** [comment]
Podes fazer o seguinte, abre uma nova tab no browser, abre as devtools e vai à tab Network, e dps clicka em XHR.

Abre a pagina do video da RTP que queres fazer download,  e na lista dos pedidos XHR vais ter um **master.m3u8**

Corres youtube-dl no URL desse ficheiro e estás safo. Podes automatizar a cena se fores artista do JS.

**Comment by plckr** [comment]
> Pelos vistos esse programa nao tem data definida, já tento ver isso :-)

Reparei nisso depois de criar a issue lol

> Podes fazer o seguinte, abre uma nova tab no browser, abre as devtools e vai à tab Network, e dps clicka em XHR.
> 
> Abre a pagina do video da RTP que queres fazer download, e na lista dos pedidos XHR vais ter um **master.m3u8**
> 
> Corres youtube-dl no URL desse ficheiro e estás safo. Podes automatizar a cena se fores artista do JS.

É isso que vou fazer, vou analisar os pedidos, obrigado 👍

**Comment by plckr** [comment]
Confirma-se, o youtube-dl funciona. Obrigado!

**Comment by falsovsky** [comment]
Viva!

**Comment by plckr** [comment]
Boas, no seguimento da nossa conversa, vim só aqui para deixar o link do script para os videos, só no caso de haver algum tipo de interesse 😄 
https://github.com/ricreis394/rtp-dl

**Comment by falsovsky** [comment]
NICE!
